### ISSUE TITLE
Can't find pry (rbenv issue?)

### ISSUE THREAD

**Issue by duncan-bayne** [jacott/emacs-pry#10]
When I run `M-x run-pry` I receive the following error:

```
Searching for program: no such file or directory, pry
```

But pry is definitely installed:

```
$ which pry
/home/duncan/.rbenv/shims/pry
```

Perhaps it's being confused by rbenv?

**Comment by cfmeyers** [comment]
I'm having the same problem.  Did you figure this one out?

**Comment by stardiviner** [comment]
@duncan-bayne You shoud check out whether rbenv is in your Emacs environment path.

**Comment by duncan-bayne** [comment]
Closing this due to age.
