### ISSUE TITLE
Two Errors and One Warning in emacs_pry.rb

### ISSUE THREAD

**Issue by gitithan** [jacott/emacs-pry#2]
When I run M-x: run-pry in emacs24 under win7 with ruby187:
## It give the Wrong info in buffer _pry_:

<b>e:/soft/editor/emacs-24.0.93/config/zzcfg.d/pry/ruby/emacs_pry.rb:78: warning: else without rescue is useless                                                  </b>
<b>exited abnormally with code 1</b>

So I opened the emacs_pry.rb in emacs ,the flymake found three places with Error or Warning, such as below:

Error_line_37:
37!  <code>proc = ->(sym) do</code>
minibuffer info: <b>syntax error, unexpected '>'</b>

Warning_line_78:
78?  <code>end</code>
minibuffer info: <b>warning: else without rescue is useless</b>

Error_line_106:
106!  <code>end</code>
minibuffer info: <b>syntax error, unexpected KEND, expecting $end</b>

How Can I fix this?

**Comment by jacott** [comment]
I'm sorry but ruby 1.8 is unsupported. I have only tested it with ruby 1.9.3.
